name: POE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List contents
        run: ls

      - name: Compile classes
        working-directory: ./src
        run: javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" ./main/Main.java ./main/Login.java ./main/Task.java  "../test/main/LoginTest.java"  "../test/main/TaskTest.java"

      - name: List contents of src directory after compile
        working-directory: ./src/main
        run: ls

      - name: Copy compiled classes to testresources directory
        working-directory: ./src/main
        run: mkdir -p ../../testresources/main && cp Main.class Login.class Task.class ../../testresources/main/

      - name: Copy compiled test classes to testresources directory
        working-directory: ./test/main
        run: mkdir -p ../../testresources/test && cp LoginTest.class TaskTest.class ../../testresources/test/

      - name: List contents of testresources directory
        working-directory: ../../testresources
        run: ls -R

      - name: Run Messages Class tests and create report
        working-directory: ./test
        run: |
          java -jar ../testresources/junit-platform-console-standalone-1.6.0.jar -cp "../testresources/main:../testresources/test" --select-class main.LoginTest main.TaskTest
