name: POE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List root directory
        run: ls -la

      - name: List all directories
        run: find . -type d

      - name: List contents of all Java files
        run: find . -name "*.java" -print

      - name: Compile classes
        run: |
          javac -cp "'./Test Libraries/junit-platform-console-standalone-1.6.0.jar'" ./src/main/Main.java ./src/main/Login.java ./src/main/Task.java "./Test Packages/main/LoginTest.java" "./Test Packages/main/TaskTest.java"

      - name: List contents of src/main directory after compile
        run: ls -la src/main

      - name: Create testresources directory
        run: mkdir -p testresources/main

      - name: Copy compiled classes to testresources directory
        run: cp src/main/Main.class src/main/Login.class src/main/Task.class testresources/main/

      - name: Copy compiled test classes to testresources directory
        run: cp src/main/LoginTest.class src/main/TaskTest.class testresources/main/

      - name: List contents of testresources directory
        run: ls -la testresources/main

      - name: Run main class tests and create report
        run: java -cp "'./Test Libraries/junit-platform-console-standalone-1.6.0.jar:testresources'" org.junit.platform.console.ConsoleLauncher --select-class main.LoginTest

      - name: Run task class tests and create report
        run: java -cp "'./Test Libraries/junit-platform-console-standalone-1.6.0.jar:testresources'" org.junit.platform.console.ConsoleLauncher --select-class main.TaskTest
